### ISSUE TITLE
Hug Bug

### ISSUE THREAD

**Issue by limelect** [kamel78/AdvancedVideoPlayer#1]
D10.2.3
While playing one try to URL another program stack.
Do not call this advance very basic program

**Comment by kamel78** [comment]
I really can't understand where is the bug in order to correct if possible, since your English is very basic !, can you please focus on the bug description and Forget about the "Basic" .....

Ps; even if it is not Advanced, it is not **_Forked_** ...

**Comment by limelect** [comment]
"since your English is very basic !,"
You are right I guess. But I do not know about you but I graduated from Columbia University.
Check it on Google if you do not know the University.
As for your bug have fun with my test and ENGLISH.
P.S i am in the business for over 40 years check my site to know who i am
www.limelect.com where you can find much free software.
I will not communicate with you any more

**Comment by kamel78** [comment]
You can escape discutions, its a very well demonstration of your programming skills ...
I am still waiting for the bug description. I already mentioned in the description that the VLC library is very buggy and the problem may be there .(I hope you have already read it).
If you are really  a good programmer as you claim, you should focus on the problem details not on anything else. No one need your comments about basic and not advanced.....
About your 40 years ,  i think that you Github profile is a good demonstation of what  **_Forking_** codes is !!!!!!, 
I dont know why you give your self the right to critic the others , but when some one tell you what you need to listen, you escape discutions. It is good when you say my code is basic, but when i say it about your english you are angry ?????..... 
The world has changed no one is better that the other ...... This is code not idiology
